/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class XShare */

#ifndef _Included_XShare
#define _Included_XShare
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     XShare
 * Method:    J2C_WrBuffer
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_XShare_J2C_1WrBuffer
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     XShare
 * Method:    C2J_WrCache
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_XShare_C2J_1WrCache
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     XShare
 * Method:    J2C_RdBuffer
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_XShare_J2C_1RdBuffer
  (JNIEnv *, jobject);

/*
 * Class:     XShare
 * Method:    C2J_RdCache
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_XShare_C2J_1RdCache
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
