/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class XShare */

#ifndef _Included_XShare
#define _Included_XShare
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     XShare
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_XShare_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     XShare
 * Method:    sumArray
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_XShare_sumArray
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     XShare
 * Method:    GetArray
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_XShare_GetArray
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
